[package]
name = "cp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rp = { path = "../rp"}
err = { path = "../err"}
mutf8 = "0.5.0"
zip = "0.5"